### ISSUE TITLE
Feature request: Desktop PWA support

### ISSUE THREAD

**Issue by matthoffner** [Ryan-yang125/ChatLLM-Web#7]
Thanks for building this! Desktop PWA support would be useful. Looking forward to using this more.

**Comment by Ryan-yang125** [comment]
Thanks @matthoffner ! I have released a new version which supports pwa, now you can download ChatLLM-Web in the location bar. I don't know much about PWA, but it looks like a good way to cache data, and I am very happly to hear more ideas about it.

**Comment by matthoffner** [comment]
Wow you move fast! Thanks again! Looking forward to contributing where I can.
